### ISSUE TITLE
some clarification

### ISSUE THREAD

**Issue by gyulaweber** [trqx/microquest#1]
Hi,

Can someone help me how to make coins? Still trying to figure out; so far, I've created quests, did them / completed them, I got XP, but no credits. 

I think it'd be nice to have some example of the usecases.

Thanks!

**Comment by trqx** [comment]
Hi,
My bad, I forgot to re-implement coin earning when doing the cli rewrite.
You make coin by doing/completing quests (between 75% and 100% of a quest value as of now).

**Comment by trqx** [comment]
you can do `pip install --upgrade microquest` to fix the problem

**Comment by gyulaweber** [comment]
cool, thanks!
